### ISSUE TITLE
[Question] Can we get the spanish phonemes in the pronucation assessment results?

### ISSUE THREAD

**Issue by marcr-exosys** [microsoft/cognitive-services-speech-sdk-js#661] opened 2023-04-10 22:20 UTC
Hi,

According to the documentation we cannot get _The syllable group, phoneme name, and spoken phoneme of pronunciation assessment are currently only available for the en-US locale._ for languages other than English. When using the SDK I do get the scores for the individual phonemes (pictures below, sorry no JSON response handy) for Spanish but it doesn't contain what the actual phoneme it is scoring against, as it does with english (english picture).

Question 1: Is there a way to access the phoneme that is was scored against using the SDK (for spanish)?
Question 2: Is there a roadmap or timeline for adding this to other languages? I have asked this a couple of times in the community forums but haven't received an answer. For background, in the US alone there are over 8 million students K-12 learning spanish, and having phoneme level breakdown is really key for delivering a pronunciation assessment product.

Any assistance is greatly appreciated.

![english](https://user-images.githubusercontent.com/26100746/231007969-55a6045f-2e6a-43ec-9109-6c572020999e.png)

![spanish](https://user-images.githubusercontent.com/26100746/231007999-197d4455-d688-4405-8c48-e8a504570dd5.png)

**Comment by glharper** [comment] 2023-04-12 13:35
@yulin-li Do we have a roadmap for complete Spanish support for phonemes in pronunciation assessments?

**Comment by yulin-li** [comment] 2023-05-03 13:26
@yinhew @wangkenpu could you please help to answer this question?

**Comment by ygorlf** [comment] 2023-05-03 23:17
I am pretty much interested in other languages phonemes as well specially on Brazilian Portuguese

**Comment by yinhew** [comment] 2023-05-04 05:51
Hi, @marcr-exosys @glharper @ygorlf

We don't expose phoneme name for non-English languages by default, and by design.
If your usage on pronunciation assessment is big enough (e.g. >1k hours per month), you can write mail to yinhew@microsoft.com, lisma@microsoft.com, wake@microsoft.com, with your subscription id.
We can add you into whitelist for showing the phoneme names.

Thanks,
Yinhe

**Comment by wangkenpu** [comment] 2023-10-10 01:16
Close the issue because of no update from the customer.

**Comment by jpalvarezl** [comment] 2024-01-16 15:31
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2101

**Closed by jpalvarezl** 2024-01-16 15:31 UTC
