### ISSUE TITLE
DirectLine Speech API

### ISSUE THREAD

**Issue by bivas6** [microsoft/cognitive-services-speech-sdk-js#282] opened 2020-11-29 16:54 UTC
Hi, 
I'm trying to use directline speech, but I cannot managed to get audio from the bot.

This is the code I use for my `activityReceived` event listener:
```
  reco.activityReceived = async (_rec, activity: sdk.ActivityReceivedEventArgs) => {
    const f = fs.createWriteStream('answer.wav')
    const b = new ArrayBuffer(1024);
    await activity.audioStream.read(b)
    f.write(Buffer.from(b))
  }
```
It seems that the `activity.audioStream.read` returns empty array.
Can you please advise? 

In addition, how should I know the length of the pullStream? 
Can you please add a sample? 

Thanks

cc: @orgads

**Comment by trrwilson** [comment] 2020-11-30 19:19
Hello!

The text-to-speech audio with a Direct Line Speech result (as provided by a `DialogServiceConnector` on its `ActivityReceived` event) is streamed as data becomes available, which may be while the text-to-speech work on the service is still happening -- this is especially true with a combination of longer prompts and high-quality voices, where it's important to have the start of audio data to play without waiting a few seconds for the prompt to complete its synthesis.

A consequence of this is that the full size of the stream isn't known in advance since the data is still being produced as you receive it.

Instead, the `PullStream` in the Speech SDK has a read behavior such that it will block until the requested number of bytes are available or the stream is complete, at which point it will return the fulfilled number of bytes (that may be zero if read is called on a completed stream). This is documented in [the reference docs for the C++/C#/Java/etc. version of the SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.pullaudiooutputstream.read?view=azure-dotnet#Microsoft_CognitiveServices_Speech_Audio_PullAudioOutputStream_Read_System_Byte___), but JavaScript's are light on details--I'll file an issue to track that.

The idea, then, is:

* Get the audio stream from the ActivityReceived event
* If it's not null or undefined, read small samples in a loop and output them via your preferred playback method
* Once you read 0 bytes, you've reached the end of the stream and are done

Similar story with the samples, where the coverage for JavaScript isn't quite as robust. But:

* [This is a demonstration of how it's done in the tests](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f01a3f8adcb41f65f51b0263695bf4bd65038d8d/tests/DialogServiceConnectorTests.ts#L402) (see `audioReadLoop` as used here)
* [This is a sample in C# that's accomplishing roughly the same thing](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/54369728cdbdceb0d6b6eb5e4824c4fb163dd078/quickstart/csharp/uwp/virtual-assistant/MainPage.xaml.cs#L107) (you likely don't need to worry about headers, though)

As for seeing empty data in the read you tried, that's likely expected:

* By default, the Speech Service will use 16kHz, 16-bit mono PCM audio -- that's 32KB/s
* Synthesized prompts have a few hundred milliseconds of silence at the beginning to facilitate natural use
* Each 100ms of silence is ~3,200 bytes, meaning that several 1024-byte reads at the beginning would be empty -- 500ms, as an example, would have about 16KB of silent reads before reaching the prompt data.

Please let us know if you still see silence as you fully consume the stream.

Thanks!!

**Comment by bivas6** [comment] 2020-12-07 16:54
Hi,
Thanks for the detailed explanation and for the code example. it was very useful.

I have couple more questions:

Is it possible to reuse `DialogServiceConnector` instance for more then one `listenOnceAsync` call?
If yes - How is it done? can I set the `DialogServiceConnector.audioConfig` with new `inputStream` and his `audioConfig`?

If it is not possible, how should I tell the bot that the 2 different `DialogServiceConnector` and the 2 different `listenOnceAsync` calls related to the same session?

Is it possible to simultaneously use  `listenOnceAsync` and `sendActivityAsync`? 
Can I cancel `listenOnceAsync` call?

Can you give some examples? 

Thanks!

**Comment by brandom-msft** [comment] 2020-12-08 22:48
You can reuse the same `DialogServiceConnector` instance for multiple calls to `listenOnceAsync`. 

- [Here is a test](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/f01a3f8adcb41f65f51b0263695bf4bd65038d8d/tests/DialogServiceConnectorTests.ts#L505) where you can see the first call made and then a second call after the first is completed. 

- Depending on your implementation, you could also place the call to listenOnceAsync on button activation. Here's a simple browser-based usage:
```
listenButton.addEventListener("click", function() {
    listenButton.disabled = true;

connector.listenOnceAsync(
      result => {
        listenButton.disabled = false;
        resultDiv.innerHTML += "\r\nFinal result: " + result.text + "\r\n";
      },
      error => {
        listenButton.disabled = false;
        resultDiv.innerHTML += error;
      }
    );
  });
```

Then each click of the button will be a new recognition. 

The above sample uses microphone input. If you're wanting to use audio files, you could configure the DialogServiceConnector from stream input and use a PullStream to feed your various files into. This would again allow you to keep the same DialogServiceConnector object since you're only changing the stream.
```
    var bytesSent = 0;
    pullStream = SpeechSDK.AudioInputStream.createPullStream( 
      {
        close: () => { return; },
        read: (buffer) => {
          if (!!sendSilence) {
              return buffer.byteLength;
          }

          var copyArray = new Uint8Array(buffer);
          var start = bytesSent;
          var end = buffer.byteLength > (fileBuffer.byteLength - bytesSent) ? (fileBuffer.byteLength - 1) : (bytesSent + buffer.byteLength - 1);
          copyArray.set(new Uint8Array(fileBuffer.slice(start, end)));
          bytesSent += (end - start) + 1;

          if (((end - start) + 1) < buffer.byteLength) {
              // Start sending silence, and setup to re-transmit the file when the boolean flips next.
              bytesSent = 0;
              sendSilence = true;
          }

          return (end - start) + 1;
        },
      });

    var audioConfig = SpeechSDK.AudioConfig.fromStreamInput(pullStream);
    connector = new SpeechSDK.DialogServiceConnector(botConfig, audioConfig);
```

The key here will be to update `fileBuffer` with your new/different audio file before you make your subsequent call to `listenOnceAsync`.

A call to `listenOnceAsync` currently cannot be canceled.

I hope these are helpful in answering your questions. Please note the above are some examples for possible uses and not meant to be complete/exhaustive, but do have a look in the [tests ](https://github.com/microsoft/cognitive-services-speech-sdk-js/tree/master/tests) directory for other examples that may be of aid. Thanks!

**Comment by brandom-msft** [comment] 2020-12-09 19:09
Closing with above response, please reach out with other questions.

**Comment by bivas6** [comment] 2020-12-10 08:59
Thanks @brandom-msft.

Can you answer to the second question about involving `listenOnceAsync` and `sendActivityAsync`?

For example, Is this flow is possible?

User                                          Bot
       sendActivityAsync >>>>>
       <<<<< Activity response
       listenOnceAsync >>>>>>
       sendActivityAsync >>>>>
       <<<<<< Audio response
       <<<<< Activity response

Thanks!

**Comment by brandom-msft** [comment] 2020-12-16 18:11
> Thanks @brandom-msft.
> 
> Can you answer to the second question about involving `listenOnceAsync` and `sendActivityAsync`?
> 
> For example, Is this flow is possible?
> 
> User Bot
> sendActivityAsync >>>>>
> <<<<< Activity response
> listenOnceAsync >>>>>>
> sendActivityAsync >>>>>
> <<<<<< Audio response
> <<<<< Activity response
> 
> Thanks!

Hi @bivas6 - I missed that one! Yes, you can make calls to sendActivityAsync and listenOnceAsync. I want to call out that the order you call them is not a guarantee of the order in return responses (if any).

**Comment by brandom-msft** [comment] 2020-12-16 18:38
> Hi @brandom-msft,
> 
> We've tried to integrate your pullStream solution in our code, but we encounter some problems.
> 
> 1. The main problem is that we don't want to send silence while we have nothing to recognize (which is your current suggestion), we would like to stop the recognition process and restart it after a while, but to stay in the same session context.

If I'm understanding this correctly, you would make a reco and at some point later you want to make another recognition within that conversation context - to do this you can set the Conversation_Conversation_Id property on the DialogServiceConnector. A conversation ID is generated on your first recognition, keep track of that and provide it on your future interaction. Let me know if I've understood/resolved this ask.

`this.properties.setProperty(PropertyId.Conversation_Conversation_Id, <some-GUID>),`

>    Do you have an example how to reuse DialogServiceConnector instance for more than one listeOnceAsync calls using PushStream? Is that even possible? We tried to implement it in a similar way to the PullStream example, but we had a lot of `close stream` errors. We think that this is might be a good solution for this problem.

I don't have an example ready-to-go that I can share at present. There is usage of a PushStream in [one of our tests ](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/d4f70a4bb7e5f3ab98cf14517f03b9aca5984e5d/tests/VoiceProfileClientTests.ts#L113), it's not for DialogServiceConnector but the basic idea there applies. Feel free to reach out in a new issue on this if you are still running into trouble.

> 2. With this line: `var end = buffer.byteLength > (fileBuffer.byteLength - bytesSent) ? (fileBuffer.byteLength - 1) : (bytesSent + buffer.byteLength - 1);`  The bot always answered to an empty string, and no recognition/recofnized CB has been called before the bot answer.
>    After changing it to this line: `var end = buffer.byteLength > (fileBuffer.byteLength - bytesSent) ? fileBuffer.byteLength  : bytesSent + buffer.byteLength;` The STT engine did trigger some recognition/recognized events, but it seemed that something is wrong, because the recognition was very poor.

I'm not sure what the issue is here, it sounds like the first part of the issue is around the bot behavior when it is sent empty audio? Can you expand on this, opening in a new issue?

> 3. Is it possible to simultaneously use listenOnceAsync and sendActivityAsync?

Answered above.

(Please note that you'll likely experience a delay in responses through the end of the year/holiday season)

**Comment by bivas6** [comment] 2020-12-23 14:35
@brandom-msft 
Hi, 
here some code example to the way we want to use both `listenOnceAsync` and `sendActivityAsync`:

```
import * as sdk from 'microsoft-cognitiveservices-speech-sdk';
import * as fs from 'fs';
import * as throttle from 'throttle';
import * as util from 'util';
import axios from 'axios';

const KEY = YOUR_SUBSCRIPTION_KEY
const sleep = util.promisify(setTimeout);
const doSendVoice = true;

async function getToken() {
  const config = {
    headers: { 'Ocp-Apim-Subscription-Key': KEY },
    timeout: 20000
  };
  const response = await axios.post(`https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken`, {}, config);
  return response.data;
}

async function main() {
  const fileName = 'test-message-16k.wav'
  const registerEvent = (reco: sdk.DialogServiceConnector) => {
    reco.recognizing = (_s: sdk.Recognizer, event: sdk.SpeechRecognitionEventArgs) => {
      console.log('hypothesis', { text: event.result.text });
    };

    reco.recognized = (_s: sdk.Recognizer, event: sdk.SpeechRecognitionEventArgs) => {
      console.debug('\r\n(recognized)  Reason: ' + sdk.ResultReason[event.result.reason] + ' Text: ' + event.result.text);
    };

    reco.sessionStarted = (_s: sdk.Recognizer, event: sdk.SessionEventArgs) => {
      const str = '(sessionStarted) SessionId: ' + event.sessionId;
      console.debug(str);
    };

    reco.sessionStopped = (_s: sdk.Recognizer, event: sdk.SessionEventArgs) => {
      const str = '(sessionStopped) SessionId: ' + event.sessionId;
      console.debug(str);
    };

    reco.speechStartDetected = (_s, event) => {
      const str = '(speechStartDetected) SessionId: ' + event.sessionId;
      console.debug(str);
    };

    reco.speechEndDetected = (_s, event) => {
      const str = '(speechEndDetected) SessionId: ' + event.sessionId;
      console.debug(str);
    };
    reco.activityReceived = (_rec, activity: sdk.ActivityReceivedEventArgs) => {
      console.log('Recieved activity ', activity.activity.text)
    };
  }
  const createReco = async () => {
    let audioConfig;
    if (doSendVoice) {
      const audioStream = fs.createReadStream(fileName);
      const pushStream = sdk.AudioInputStream.createPushStream();
      const handleData = (buf: Buffer) => pushStream.write(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
      const throt = new throttle(32000);

      audioStream
        .pipe(throt)
        .on('data', handleData)
        .once('close', () => {
          console.log('close')
          pushStream.close();
          audioStream.removeListener('data', handleData);
        });
      audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
    }
    const authToken = await getToken();
    const botConfig = sdk.BotFrameworkConfig.fromAuthorizationToken(authToken, 'westus2')
    const reco = new sdk.DialogServiceConnector(botConfig, audioConfig)
    registerEvent(reco);
    if (doSendVoice)
      reco.listenOnceAsync(undefined, (e) => console.error(e))
    return reco
  }

  // Try simulataneously call listenOnceAsync and sendActivityAsync
  const reco = await createReco();
  await sleep(100);
  reco.sendActivityAsync(JSON.stringify({
    type: 'event',
    name: 'DTMF',
    value: '5'
  }));
}
main().catch((r) => console.error(r))
```

With `doSendVoice = true` we are not getting any response to `sendActivityAsync`, but if we set it to false, we do recieve the expected response.

Can you advise? are we doing it wrong?

**Comment by bivas6** [comment] 2021-01-06 13:28
@brandom-msft ping

**Comment by orgads** [comment] 2021-02-09 07:27
No longer reproduces with 1.15. Please close.

**Closed** 2021-03-22 23:06 UTC
