### ISSUE TITLE
Websockets error when using Custom Speech models

### ISSUE THREAD

**Issue by nrobert** [microsoft/cognitive-services-speech-sdk-js#76] opened 2019-07-26 11:45 UTC
Hello,

We have developed in May-June a web application which is using Speech input. On this web app we can select default endpoint or Custom Speech models, and the implementation is using the same lib (just setting the `speechConfig.endpointId` when using custom).

For a few days now, we are facing the following error when using the Custom Speech models (we don't have this error when using default model provided by Microsoft):
> WebSocket is already in CLOSING or CLOSED state.

This error is thrown by `microsoft.cognitiveservices.speech.sdk.bundle.js:2523`

Details:

- The error is happening when using `recognizeOnceAsync` or `startContinuousRecognitionAsync`
- We were using the JS SDK 1.5.0, I tried to update to 1.6.0 but we still got the same error.
- Test environment: Chrome navigator on Mac and Windows (up-to-date, which is version 75.0.3770.142 today)
- Our Custom Speech models are running and the "Check endpoint" feature on Speech portal, used with a wav file, is working successfully
- I also checked our API Key and model endpointId: they did not change

We have no idea on how we could further investigate.

**Comment by nrobert** [comment] 2019-07-26 12:12
More details about an example case:

Error with Custom Speech endpoint:
- SessionId: "04BD03B3DF6E485BA038C0FCD8AB1EEB"
- Date & Time: 26/07/2019 - 14h10 - Paris Timezone (UTC+2)

Ok with default Speech, from the same webpage:
- SessionId: "ED86021CAE6546B89F83BB636C81A9C9"
- Date & Time: 26/07/2019 - 14h11 - Paris Timezone (UTC+2)

**Comment by eldakms** [comment] 2019-07-26 12:15
let me investigate and come back to you

**Comment by eldakms** [comment] 2019-07-26 12:23
Thank you for detailed input. The issue is on our side and will be fixed within the hour. I will post back when this happens.

**Comment by eldakms** [comment] 2019-07-26 13:18
The fix has been deployed to prod. I would appreciate if you could confirm from your side. Thank you very much and we are very sorry for the inconvenience.

**Comment by nrobert** [comment] 2019-07-26 13:20
I made a quick test, it seems fixed yes.

**Comment by eldakms** [comment] 2019-07-26 13:22
Thank you! If you see any inconsistencies or bump into any issues, please contact us and we will investigate and fix ASAP.

**Closed** 2020-03-22 18:21 UTC
