### ISSUE TITLE
Add Releases to GitHub

### ISSUE THREAD

**Issue by robinmanuelthiel** [Microsoft/cognitive-services-speech-sdk-js#16] opened 2018-12-24 00:30 UTC
Currently, you are only offering releases as a download on the docs.microsoft.com pages, which is pretty unuseful, as I can't get noticed about new releases and it breaks the media between GitHub and MS Docs. I would suggest, to also use GitHub's Releases feature and also publish new releases there.

**Comment by wolfma61** [comment] 2018-12-24 08:07
Duplicate of #17

**Closed by wolfma61** 2018-12-24 08:07 UTC
