### ISSUE TITLE
Instance is shutting down errors

### ISSUE THREAD

**Issue by bivas6** [microsoft/cognitive-services-speech-sdk-js#453] opened 2021-11-09 16:01 UTC
Hi,

Once in a while (it is not reproduced consistently), the 'cancel' callback of our speech-to-text client is called with the following error:
```Reason: Error. sessionId: ... errorCode: ConnectionFailure. Details: Instance is shutting down websocket error code: 1012 ```

Can you explain it? Is there something we can do in the client to overcome it? Do you know if restarting the current request will solve the issue (for example, by reaching a different instance)? 

Thanks!

**Comment by glharper** [comment] 2021-11-10 17:10
@bivas6 Thanks for using SpeechSDK, and writing this up. A few questions:
Could you provide example code and a wav file for reproducing this (even if the wav file doesn't repro it every time)? 
How long can your recognition sessions last? 
How long can silences in your recognition sessions last?

**Comment by bivas6** [comment] 2021-11-11 12:15
Hi @glharper, thanks for the quick reply.

I don't have a specific wav file to reproduce it, as the issue occured during a normal flow in our client setup, but I don't think it is a specific wav that caused this. 
In this session, the recognition session last ~37 seconds, and the error received right after 'recognized' callback called (about 10 ms).
No silence in this specific session.

In the previous time it occurs, it happened 3 times around the same time, then 10 minutes later another 5 times, and then arbitrary failures in the next 30 minutes. 
Some of theses sessions last long (10 minutes), and few of them had silence, but not in the first and not in every one of it. 

Do you think the length of the recognition-sessions has something to do with this issue?

**Comment by glharper** [comment] 2021-11-11 16:28
@bivas6 Thanks for the response. 1012 is an odd error to get, especially multiple times, since it means the service is shutting down. Which region are you seeing this on? Is this still ongoing, or did you only see the 1012 failures last week?

I will forward your answers onto our service team. A few session ids may help them figure out what's happening, if you saved them.

**Comment by bivas6** [comment] 2021-11-14 17:35
Hi @glharper 

AFAIK, it occurred 2 different times. 

First time in the 4.10.21, it occurs multiple times in `centralus` region. some session ids (I have some more): `2C145B527316402B91077CA984ABF55A`, `FB796048C5ED45148B570C35F3415204`, `AFA3E9141269440380BDC7C34986B71A`.
SDK version: `1.17.0`

Second time was in the 29.10.21 in `westeurope` region. Session id: `E0E646011F40470389D0C0BC4609F3C8`.
SDK version: `1.16.0`

Thanks

**Comment by glharper** [comment] 2021-11-15 17:42
@bivas6 Thanks for the session ids. Unfortunately, our logs only go back 30 days or so, so the only session id I could find was E0E646011F40470389D0C0BC4609F3C8 on 1.16. The service does send a 1012, and then the connection closes prematurely, which makes sense, since 1.16 doesn't have reconnection logic (added in 1.17). 

If you have any session IDs from the last 30 days for 1.17 or later, at the very least I can see if the reconnect attempts are happening as expected. A repro with 1.19 would be even better, as we have some long-running connection fixes in that version.

**Comment by bivas6** [comment] 2021-11-16 08:22
@glharper Thanks, I'll let you know if it occurs again with different SDK version.

**Comment by glharper** [comment] 2021-12-01 18:57
@bivas6 Any updates on this issue? If not, I'll close it.

**Closed** 2021-12-03 17:53 UTC
Labels: pending close

**Comment by bivas6** [comment] 2021-12-06 13:10
@glharper sorry for the late response. It is not reproduces for us. If it will occur again, I'll let you know.

Thanks!
