### ISSUE TITLE
Suggestions: MicAudioSource to accept caller passing an owned AudioContext for better permissions control and persistence in Safari

### ISSUE THREAD

**Issue by compulim** [microsoft/cognitive-services-speech-sdk-js#571] opened 2022-09-28 22:45 UTC
In Safari, creating an `AudioContext` will trigger permission dialog. Also, `AudioContext` may change state to `suspended` if there is no user gesture on the page (for privacy reasons).

If the web app could pass a `AudioContext` to `MicAudioSource`, we could:

- Ask microphone privilege at a more convenient time (a.k.a. first-time blessing)
- Reduce repetitively asking for microphone privilege across recognitions (a.k.a. persisted blessing)
- Resume `AudioContext` whenever the web app detects user gesture, to prevent staled recognition due to suspended `AudioContext`

This could also mean the `MicAudioSource` will no longer own the `AudioContext`. That means, it should not close/suspend `AudioContext` after `MicAudioSource.turnOff()` is being called.

When the `AudioContext` is owned by the web app, the app developer should understand it is their responsibility to keep the `AudioContext` opened/resumed/cleaned/isolated. They should not mix-and-match different audio processing into the same `AudioContext` object as it could cause undesirable side effects.

**Comment by glharper** [comment] 2022-09-29 13:24
@compulim Thanks for using JS Speech SDK, and writing up this feature request. Some comments:

- Changing the MicAudioSource API and/or default behavior would break a lot of existing users for modest gain (JS Speech SDK supports all major browsers on all major operating systems, most of which don't have the same AudioContext idiosyncrasies).
- Adding a new ContextAudioSource class is a possibility, but clearly communicating the specific edge cases and behavior differences above will be a challenge, with increased load on our team for customer support for this class
- None of this addresses the root cause of the issue, which is the unique constraints Apple puts on media classes in Safari. I could spend X weeks implementing this, only to have Apple change Safari media behavior the day after my implementation is checked in.

Having said that, I will discuss internally about the value of adding a new AudioSource class/API.

**Comment by compulim** [comment] 2022-09-29 20:22
Thanks for your insights and spending time writing it out. Appreciated.

Do you know if there is a way we could keep the instance of `MicAudioSource` alive?

I know the `AudioContext` get closed after `turnOff()`. Is there a way we could perform multiple recognitions without turning it off?

**Comment by glharper** [comment] 2022-09-29 22:05
@compulim Looking at this a bit more, the new API surface seems minimal. Please look at the draft PR above and let me know your thoughts.

**Comment by compulim** [comment] 2022-09-30 01:03
Yes! This is what I think should work. I don't know the audio gating part though.

You and me had been invested many hours into understanding how `AudioContext` actually works in Safari. 😂 While I understand their desire to make microphone privacy better, IMO, they are stepping too much into gray area and lack of documentation or samples. It negated most of their effort.

Excited with your work. The code in this repository inspired me a lot on audio processing with Web Audio: interleaving, floating point vs. 16-bit, RIFF WAV header, etc. Thank you for your hard work.

**Comment by glharper** [comment] 2022-10-19 21:36
@compulim I've added this to our backlog as internal ref. #4598532. Remaining work is to add a test for this API and get it passing.

**Comment by glharper** [comment] 2023-10-04 16:09
@compulim The PR still needs tests added, and I didn't update as I'm concerned that adding this API could introduce a large bug vector into the SDK when the AudioContext is in a state not conducive to accepting input audio.

If this is still needed and you'd like to propose methods to address this concern, please re-open.

**Closed by glharper** 2023-10-04 16:09 UTC
Labels: enhancement
