### ISSUE TITLE
[bug] safari microphone startContinuousRecognitionAsync has delay

### ISSUE THREAD

**Issue by ysheep-js** [microsoft/cognitive-services-speech-sdk-js#663] opened 2023-04-13 08:25 UTC
bug Description:

I have a component of SpeechRecognizer from microphone. It works well in chrome but seems not good in safari.
When I click button to record, it has 1s-5s delay for connecting websocket.
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/65909463/231699722-640e1e76-a43b-4ec6-985d-791811a7b367.png">
It will cause user's first sentence cannot be recognized sometimes.
However in chrome seems good.
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/65909463/231700280-863b19e7-79c8-4ea8-9169-da6f2cad20d3.png">
There is no connection delay in chrome

Code:

```
const subscriptionRegion = 'eastus';
const speechConfig = SpeechSDK.SpeechConfig.fromAuthorizationToken(
    subscriptionAccessToken?.accessToken,
    subscriptionRegion
);
speechConfig.speechRecognitionLanguage = targetLang;
const audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
const recognizer = useRef<SpeechSDK.SpeechRecognizer | null>();
const { recognizedText, setRecognizedText, partialText, setPartialText } = useContext(RecognizedTextContext);

useEffect(() => {
    if (!recognizer.current) {
        recognizer.current = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
        recognizer.current.recognizing = (reco, e) => {
            const res = e.result;
            if (res.text) {
                setPartialText(res.text);
            }
        };

        recognizer.current.recognized = (reco, e) => {
            const res = e.result;
            if (res.text) {
                setRecognizedText(
                    (prevRecognizedText: string) => prevRecognizedText + ' ' + partialText + ' ' + res.text
                );
                setPartialText('');
            }
        };
    }
}, [audioConfig, isRecording, partialText, recognizedText, setPartialText, setRecognizedText, speechConfig]);

const handleVoiceInput = useCallback(async () => {
    const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
    const mimeType = isSafari ? 'audio/mp4' : 'audio/webm';

    // TODO: using real-time speech to text not working well on Safari
    if (!isRecording) {
        setIsRecording(true);
        setRecognizedText('');
        recordedChunks.current = [];
        // Comment for the time being
        // await createWaveSurferInstance();
        navigator.mediaDevices.getUserMedia({ audio: true }).then(async (micStream) => {
            if (recognizer.current) {
                recognizer.current.startContinuousRecognitionAsync();
            }
            setStream(micStream);
            const mediaRecorder = new MediaRecorder(micStream, { mimeType });

            mediaRecorder.ondataavailable = async (event: BlobEvent) => {
                recordedChunks.current.push(event.data);
                // Send Blob to waveSurfer
                if (waveSurferInstance.current) {
                    const audioBlob = new Blob(recordedChunks.current, { type: 'audio/webm' });
                    waveSurferInstance.current.loadBlob(audioBlob);
                }
            };
            mediaRecorder.start(1000);
        });
    } else {
        setIsRecording(false);
        if (recognizer.current) {
            recognizer.current.stopContinuousRecognitionAsync();
        }
        stream?.getTracks().forEach((track) => track.stop());
        setStream(null);

        const recordedBlob = new Blob(recordedChunks.current, { type: 'audio/webm' });

        const audio = await blobToBase64(recordedBlob);
        setIsSendingMessage(true);

        const textToSend = partialText.length > recognizedText.length ? partialText : recognizedText;
        setMessages((prevMessage: Message[]) => {
            return [...prevMessage, { role: 'user', content: textToSend, replies: [], audio: '' }];
        });

        const result = await sendVoiceMessage({
            data: { audio, transcribedText: textToSend },
            token: accessToken,
        });
        setMessages(result.messages);
        setIsSendingMessage(false);
        setRecognizedText('');
        // clear recordedChunks after transcribed
        recordedChunks.current = [];
    }
}, [
    accessToken,
    isRecording,
    partialText,
    recognizedText,
    sendVoiceMessage,
    setIsRecording,
    setIsSendingMessage,
    setMessages,
    setRecognizedText,
    stream,
]);
```
Platform, Operating System, and Programming Language
MacOS - Monterey 12.6
Nextjs 13.1.6
Node 18.14.1
microsoft-cognitiveservices-speech-sdk: 1.26.0

Looking forward to any advice!

**Comment by glharper** [comment] 2023-04-13 15:25
@ysheep-js Thanks for using Speech SDK, and writing this issue up. Is this a duplicate of #622?

**Comment by ysheep-js** [comment] 2023-04-17 03:35
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/65909463/232370816-a76c9b70-0434-4434-8aba-dad2f947aa29.png">
Here in chrome seems the WebSocket connection was suddenly lost for the first three attempts. It will happen sometimes.

**Comment by ysheep-js** [comment] 2023-04-17 04:04
@glharper I test on microsoft demo, seems there are same problems
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/65909463/232375242-3b1fb7dc-8725-4488-b0a9-b58f53dc0d10.png">
Here is demo website: https://speech.microsoft.com/portal/speechtotexttool

**Comment by ysheep-js** [comment] 2023-04-17 06:32
I found the problem: Quota exceeded. Cid:  websocket error code: 1007

**Closed** 2023-04-25 16:37 UTC
