### ISSUE TITLE
The function crashes with ENOMEM when requiring the SDK

### ISSUE THREAD

**Issue by calbertts** [microsoft/cognitive-services-speech-sdk-js#405] opened 2021-07-16 16:20 UTC
**Describe the bug**
The function crashes once the SDK is required because of a memory issue:
```
const sdk = require('microsoft-cognitiveservices-speech-sdk');
```

**To Reproduce:**
Create a durable function, and one of the activity functions, has to require the SDK, that's it.

The logs we have:
```
2021-07-16T16:19:32.433 [Error] Executed 'Functions.MYFUNC' (Failed, Id=xxx, Duration=11ms)Result: FailureException: Worker was unable to load function MYFUNC: 'SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOMEM (not enough memory)'Stack: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOMEM (not enough memory)at Object.userInfo (os.js:272:11)at Function.module.exports.os (C:\home\site\wwwroot\node_modules\username-sync\index.js:24:17)at module.exports (C:\home\site\wwwroot\node_modules\username-sync\index.js:7:25)at Object.<anonymous> (C:\home\site\wwwroot\node_modules\async-disk-cache\index.js:26:42)at Module._compile (internal/modules/cjs/loader.js:999:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)at Module.load (internal/modules/cjs/loader.js:863:32)at Function.Module._load (internal/modules/cjs/loader.js:708:14)at Module.require (internal/modules/cjs/loader.js:887:19)at require (internal/modules/cjs/helpers.js:74:18)
```

**Expected behavior**
This started on Wednesday at noon, the function should require the SDK without crashing because of a memory issue

Version of the Cognitive Services Speech SDK
1.17.0

**Platform, Operating System, and Programming Language**

On Azure where is failing:
OS: Windows
Programming language: NodeJS

Locally where is working:
OS: MacOS
Programming language: NodeJS

These are my 7 days logs of memory usage:
![image](https://user-images.githubusercontent.com/1326651/125976886-63fe98af-08be-4d48-80f8-64d76adfcb24.png)

**Comment by glharper** [comment] 2021-07-16 16:45
@calbertts Thanks for using SpeechSDK, and writing this issue up. This appears to be a duplicate of [this issue](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/390)

Out of curiosity, which version of Node is your Azure deployment running? Looking at [this upstream issue](https://github.com/nodejs/node/issues/25382), increasing the memory on your instance may work for Node > 10.

**Comment by calbertts** [comment] 2021-07-19 07:50
Thanks for the feedback.
The NodeJS version we're currently using is 12 LTS, we also have tried to increase the instance memory but it didn't work, keep in mind our function doesn't crash on the deployment stage, but when the function invoked.

Regards

**Comment by glharper** [comment] 2021-07-19 14:33
@calbertts If the Node issue I linked to above is truly the culprit, downgrading to Node 10 *should* mitigate this. Would be useful to know on my end. As mentioned before, there doesn't seem to be a clear cut way to fix this in Speech SDK.

**Comment by glharper** [comment] 2021-07-21 19:59
@calbertts Testing my own deployment with this, a call to os.userInfo().username (without the require("microsoft-cognitiveservices-speech-sdk") statement will cause the same crash. Downgrading to Node 10 doesn't seem to help, but switching over to a linux instance does.

**Comment by glharper** [comment] 2021-08-03 20:32
@calbertts Please regen your package-lock.json file, the fix for this issue in username-sync should get picked up, and version 1.0.3 of that library, which shouldn't crash your app service instance, will be used. Thanks for opening this issue!

**Closed by glharper** 2021-08-03 20:32 UTC
Labels: question
