### ISSUE TITLE
Question STT doesn't work in my React App when deployed

### ISSUE THREAD

**Issue by Yousseffakhry20** [microsoft/cognitive-services-speech-sdk-js#720] opened 2023-08-22 11:05 UTC
I am using STT service in my React App and it's working fine in development.
But when I build it and use it in production the STT doesn't work at all and it doesn't even ask for Mic permission.

It works fine in localhost but when the build is deployed it doesn't work

**Comment by glharper** [comment] 2023-08-22 11:17
@Yousseffakhry20 Thank you for using the Speech SDK, and writing this issue up. Would you be able to debug into your production app (or at least catch errors and log them) to give a better idea what the issue could be?

**Comment by Yousseffakhry20** [comment] 2023-08-22 11:25
Ok I forgot to mention another detail, the Speech-To-Text method keeps waiting for speech with "Speak into your Microphone" text displayed but doesn't actually stop or timeout. Which leads to no actual error but at the same time it's not working or recognizing any speech.

**Comment by glharper** [comment] 2023-08-22 12:36
@Yousseffakhry20 A couple of comments:
- You seem to be referring to application code that you haven't shared. Is there a template or repo you're referring that you believe we support?
- If your application is working locally, but not in a different environment, the issue is probably environment configuration. Our Speech SDK code hasn't changed in the deployment process. Details about your production environment may be helpful, but to be of any assistance we'll need logs and actual error messages/codes from the Speech SDK. 

You can turn on logging by adding:
```sdk.Diagnostics.SetLoggingLevel(sdk.LogLevel.Debug);``` before SpeechRecognizer instantiation, and you should see console output from the SDK.

**Comment by glharper** [comment] 2023-08-25 14:48
Closing this pending response from submitter.

**Closed by glharper** 2023-08-25 14:48 UTC
Labels: question, pending close
